sudo: required

language: c

services: docker

install:
    - docker build . -t tests --build-arg PG_VERSION=${PG_VERSION}

script:
    - docker run tests

env:
    - PG_VERSION=12
    - PG_VERSION=11
    - PG_VERSION=10
    - PG_VERSION=9.6
    - PG_VERSION=9.5
    - PG_VERSION=9.4
