-- base36 conversion should encode integer;
SELECT 120::base36;
-- base36 conversion should decode text;
SELECT '3c'::base36::int;
-- base36 conversion should error to big values;
SELECT '3caaaaaaaaaaaaa'::base36::bigint;
-- base36 conversion should cast big base36 values;
SELECT 'zik0zj'::base36::int;
-- base36 conversion should cast big int values;
SELECT 2147483647::base36;
-- base36 conversion should error to big values;
SELECT 'zik0zk'::base36::int;
-- base36 conversion should error invalid values;
SELECT '3&'::base36::bigint;
-- base36 comparison should compare using >;
SELECT 'a'::base36 > 'b'::base36;
-- base36 comparison should compare using <;
SELECT 'a'::base36 < 'b'::base36;
-- base36 negative values should convert from base36;
SELECT '-zik0zj'::base36::int;
-- base36 negative values should convert from ints;
SELECT '-2147483647'::integer::base36;
